name: CI

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2

      - name: Checkout config files
        uses: actions/checkout@v2
        with:
          repository: rolling-scopes-school/basic-nodejs-2021Q2
          ref: course-template-ci
          path: config2021q2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm ci

      - name: Check ESLint rules
        run: npx eslint --no-inline-config --config config2021q2/.eslintrc.json --ext .js,.ts src

      - name: Check if TypeScript files compiles (conditional)
        run: if find src -type f -name *.ts | grep .; then npx tsc --noEmit --project config2021q2; fi
